### ISSUE TITLE
cross tests: multiplexing: enabled multiplexing tests for CL

### ISSUE THREAD

**Issue by dkochmanski** [TurtleWarePL/thrift#12]
How to use mulitplexing protocol:

```
CL-USER> (thrift:serve #u"thrift://127.0.0.1:9090"
                       tutorial:calculator
                       :multiplexed t)

;;; in another REPL
CL-USER> (thrift:with-client
          (prot #u"thrift://127.0.0.1:9090" :multiplexed t)
          (tutorial.calculator:add prot 2 3))
5
```

note, that method add is implemented in `tutorial.calculator-implementation`, and request is defined in `tutorial.calculator` to always provide separate method namespaces for services.

Structures are defined in top-level package `tutorial`, same as variables containing service instances.

**Comment by dkochmanski** [comment]
I've added status and tutorial to `wiki`.

**Comment by uint** [comment]
Added in #13.
