### ISSUE TITLE
cl-lib: use trivial-gray-streams

### ISSUE THREAD

**Issue by dkochmanski** [TurtleWarePL/thrift#4]
we use implementation conditionals for different gray-stream packages. We should use trivial-gray-streams portability layer.

- [x] identify places using gray methods
- [x] replace them with tgs
- [x] bundle tgs with the software

**Comment by uint** [comment]
I've been poking at this. It looks like the methods provided by trivial-gray-streams only specialize on instances of `trivial-gray-streams:fundamental-stream` (or its children) and can't really be used as a portability layer for implementation-specific streams (that usocket, for example, provides us with).

```
  Failure 1: UNEXPECTED-ERROR when running BASE-TYPES::TYPEDEF-TEST
    There is no applicable method for the generic function
      #<STANDARD-GENERIC-FUNCTION TRIVIAL-GRAY-STREAMS:STREAM-WRITE-SEQUENCE (1)>
    when called with arguments
      (#<SB-SYS:FD-STREAM for "socket 127.0.0.1:36370, peer: 127.0.0.1:39379" {1002A4EB63}>
       #<unknown pointer object, widetag=#x17 {7FFFF6CDED6F}> :START 0 :END NIL).
```

It's possible I don't really understand how this is supposed to work, though.
